runtime: nodejs20
instance_class: F1
handlers:
  # Xử lý tất cả các đường dẫn cho tài nguyên tĩnh
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot))
    static_files: build/\1
    upload: build/(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot))
    secure: always

  # Điều quan trọng: xử lý tất cả các đường dẫn khác, trả về index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
